#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"


FONT_FACE="JetBrainsMono Nerd Font"
FONT_FACE_2="Berkeley Mono"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"



sketchybar --bar \
    height=24 \
    color=0x66494d64 \
    margin=0 \
    sticky=on \
    padding_left=0 \
    padding_right=0 \
    notch_width=188 \
    display=all   \
    position=bottom
    # y_offset=6



sketchybar --default \
    background.height=32 \
    icon.color=0xff24273a \
    icon.font="$FONT_FACE:Medium:20.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=0xff24273a \
    label.font="$FONT_FACE_2:Bold:14.0" \
    label.y_offset=1 \
    label.padding_left=0 \
    label.padding_right=5


sketchybar --add item current_space left \
    --set current_space \
    background.color=0xffb4befe  \
    script="$PLUGIN_DIR/current_space.sh" \
    --subscribe current_space space_change display_change mouse.clicked

    # label.drawing=off \

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xfff5c2e7 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
   label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:16.0" \
    label.color=0xffcad3f5 \
    # icon=\
    # icon.color=0xfff5c2e7 \
    # icon.font="$FONT_FACE:Bold:24.0" \
    # icon.padding_left=0 \
    # icon.padding_right=0 \
    # icon.y_offset=0 \
    # label.padding_left=5

    sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    background.color=0xffb4befe \
    update_freq=10 \
    script="$PLUGIN_DIR/clock-minimal.sh"
#    icon=󰃰 \
#    script="$PLUGIN_DIR/clock.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
sketchybar --trigger front_app_switched
sketchybar --trigger display_change

